deployment:
  kind: Deployment
  replicas: 1
  image: docker.io/ezconnect/webhook
  imagePullSecrets: []
  pullPolicy: IfNotPresent
  env: {}
  liveness: {}
  readiness: {}
service:
  type: ClusterIP
  ports:
    http:
      port: 8080
ingress:
  enabled: false
  hosts: {}
persistent:
  enabled: false
  volumes: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
affinity: {}
tolerations: []
resource: {}
autoscaling:
  enabled: false
  min: 1
  max: 3
  cpu: 0.5
  memory: 0.5
serviceAccount:
  enabled: false
